### ISSUE TITLE
Module breaking standard console output (ISE)

### ISSUE THREAD

**Issue by therealxelias** [nightroman/SplitPipeline#20] opened 2018-07-20 17:50 UTC
I'm running into a scenario where once a call for SplitPipeline has finished executing I find myself unable to get the console window of the ISE to provide standard output... I'm able to fix it by restarting PS but that isn't exactly an ideal solution.

This seems to impact anything plainly supplied to the console:

eg. 
`> "Hi"`
returns nothing

As well as explicit Write-Output calls. Alternative output methods such as Write-Host are seemingly not impacted by this.

Any assistance would be appreciated.

**Comment by nightroman** [comment] 2018-07-21 01:32
ISE is obsolete and not being developed anymore, as far as I know. VSCode with the PS extension is the recommended replacement. Can you see the same problem in the real console or VSCode terminal or its PS extension console? Try using them.

As for ISE, I cannot reproduce the issue and I have no idea how to help, sorry. Can you at least help me to reproduce? Otherwise, I will close this issue as "won't fix / cannot repro".

**Closed** 2018-07-25 15:35 UTC
